name: auto-build-PDS_MR
on:
  workflow_dispatch:
  schedule:
    - cron: 0 4 * * 5
jobs:
  env:
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      contents: write
    env:
      python-version: '3.13'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install imagemagick (convert)
        run: |
          python get.py
