name: getsoda
on:
  workflow_dispatch:
  schedule:
    - cron: 0 4 * * 5
jobs:
  build-and-test:
    runs-on: ubuntu-latest # 推荐使用最新的 Ubuntu 长期支持版本
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # 使用 actions/checkout@v4 来获取你的代码
    - name: Set up Python
      uses: actions/setup-python@v5 # 使用 actions/setup-python@v5 来设置 Python 环境
      with:
        python-version: '3.12' # 指定你需要的 Python 版本，例如 3.8, 3.9, 3.10, 3.11, 3.12。建议使用一个稳定且较新的版本。
        # cache: 'pip' # 启用 pip 缓存，可以加快后续运行的速度
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip # 升级 pip
    - name: Install Playwright
      run: |
        pip install playwright # 安装 Playwright 库
        playwright install      # 安装 Playwright 浏览器驱动（Chromium, Firefox, WebKit）
    - name: Run getsoda
      run: |
        python getsoda.py
    - name: Commit changes
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        DATE=$(date +%Y-%m-%d)
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add api_responses.json
        git commit -m "Add json file on $DATE"
        git push origin HEAD
